require 'resque/tasks'
require 'redis'
require 'json'
require 'mail'

require_relative './lib/util'
require_relative './lib/parser/page'
require_relative './lib/parser/url'
require_relative './lib/generator/generator'
require_relative './workers/sitemap_worker'